 #yamllint disable rule:comments-indentation
theme: auto
default_redirection_url: {{DEFAULT_REDIRECTION_URL}}

server:
  address: 'tcp://:9091'

# log:
#   level: debug

totp:
  issuer: {{DOMAIN}} #your authelia top-level domain
  period: 30
  skew: 1

identity_validation:
  reset_password:
    jwt_secret: '{{JWT_SECRET}}'

authentication_backend:
  disable_reset_password: false
  # refresh_interval: 5m
  file:
    path: '/config/users_database.yml'
    password:
      algorithm: argon2id
      key_length: 32
      iterations: 2
      salt_length: 16
      parallelism: 2
      memory: 512

access_control:
  default_policy: deny
  rules:
    - domain: "{{AUTH_HOST}}" #This should be your authentication URL
      policy: bypass #Do not ask for credentials
    - domain: "{{PROTECTED_HOST}}" #domain to protect
      policy: one_factor

session:
  name: authelia_session
  secret: '{{SESSION_SECRET}}'
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: {{DOMAIN}}  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: '{{STORAGE_SECRET}}'

notifier:
  filesystem:
    filename: /config/notification.txt